import os
import pickle
from pathlib import Path
from utils.logger import setup_logger

logger = setup_logger("youtube_upload")

class YouTubeUploader:
    def __init__(self, config):
        self.config = config
        self.youtube_config = config.get("youtube", {})
        self.upload_config = config.get("upload", {})
        self.youtube = None

    def _authenticate(self):
        try:
            from google_auth_oauthlib.flow import InstalledAppFlow
            from google.auth.transport.requests import Request
            from googleapiclient.discovery import build
            SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]
            credentials = None
            token_path = Path(self.config.get("output_dir", ".")) / "youtube_token.pickle"
            if token_path.exists():
                with open(token_path, "rb") as f:
                    credentials = pickle.load(f)
            if not credentials or not credentials.valid:
                if credentials and credentials.expired and credentials.refresh_token:
                    credentials.refresh(Request())
                else:
                    client_config = {"installed": {
                        "client_id": self.youtube_config["client_id"],
                        "client_secret": self.youtube_config["client_secret"],
                        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                        "token_uri": "https://oauth2.googleapis.com/token",
                        "redirect_uris": ["urn:ietf:wg:oauth:2.0:oob", "http://localhost"],
                    }}
                    flow = InstalledAppFlow.from_client_config(client_config, SCOPES)
                    credentials = flow.run_local_server(port=0)
                with open(token_path, "wb") as f:
                    pickle.dump(credentials, f)
            self.youtube = build("youtube", "v3", credentials=credentials)
            logger.info("YouTube API authenticated")
            return True
        except Exception as e:
            logger.error(f"YouTube auth failed: {e}")
            return False

    def upload(self, video_path, script):
        if not self._authenticate():
            return {"status": "error", "message": "Authentication failed"}
        title = script.get("title", "Amazing Facts")
        if len(title) > 100:
            title = title[:97] + "..."
        tags = script.get("tags", []) + self.upload_config.get("default_tags", [])
        hashtag_str = " ".join(f"#{t}" for t in tags[:10])
        description = f"{title}\n\n{hashtag_str}\n\nSubscribe for more!\n\n---\nAuto-generated by Auto Content Creator"
        body = {
            "snippet": {"title": title, "description": description[:5000], "tags": tags[:500], "categoryId": self.upload_config.get("category_id", "28")},
            "status": {"privacyStatus": self.upload_config.get("privacy", "public"), "selfDeclaredMadeForKids": False},
        }
        try:
            from googleapiclient.http import MediaFileUpload
            media = MediaFileUpload(video_path, chunksize=-1, resumable=True, mimetype="video/mp4")
            logger.info(f"Uploading: {title}")
            request = self.youtube.videos().insert(part="snippet,status", body=body, media_body=media)
            response = None
            while response is None:
                status, response = request.next_chunk()
                if status:
                    logger.info(f"  Progress: {int(status.progress() * 100)}%")
            video_id = response["id"]
            video_url = f"https://www.youtube.com/shorts/{video_id}"
            logger.info(f"Upload complete: {video_url}")
            return {"status": "success", "video_id": video_id, "url": video_url, "title": title}
        except Exception as e:
            logger.error(f"Upload failed: {e}")
            return {"status": "error", "message": str(e)}
